implemented search, update and delete methods in BookController
vaniii1/online-book-store pull request #3
Opened 2023-09-07 15:09 UTC by vaniii1

2023-09-11 14:23 UTC, aaananas requested changes

2023-09-11 14:23 UTC, aaananas commented on src/main/java/com/example/onlinebookstore/dto/BookSearchParametersDto.java
> +                                      String[] lowestPrice, String[] greatestPrice) {
```suggestion
public record BookSearchParametersDto(
                 String[] titles, 
                 String[] authors,
                 String[] lowestPrice, 
                 String[] greatestPrice) {
```

2023-09-11 14:23 UTC, aaananas commented on src/main/java/com/example/onlinebookstore/repository/book/BookRepository.java
> +                @Param("description") String description, @Param("coverImage") String coverImage);
you can use ```save``` method to update an entity

2023-09-12 16:40 UTC, Ivan95kos approved these changes
Great job

2023-09-12 16:52 UTC, merged